customer_shopping_behavior

In [31]:
import pandas as pd
df=pd.read_csv('C:/Users/rajib/Downloads/customer_shopping_behavior.csv')

In [32]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [33]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [35]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

Replace the Missing values with median category wise

In [36]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [37]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

Clean columns name into lower casing and spaces with underscores

In [38]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ', '_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [39]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [40]:
#Create a new column aged_group
labels=['Young Adult','Adult','Middle-aged','Senior']
df['aged_group']=pd.qcut(df['age'],q=4,labels=labels)

In [41]:
df[['age','aged_group']].head(10)

   age   aged_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [42]:
#Purchased frequency days

frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 months':90
}
df['purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [43]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [44]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [45]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [46]:
df=df.drop('promo_code_used',axis=1)

In [47]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'aged_group', 'purchase_frequency_days'],
      dtype='object')

In [49]:
!pip install pyodbc mssql-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in c:\programdata\anaconda3\lib\site-packages (5.3.0)
Requirement already satisfied: mssql-python in c:\users\rajib\appdata\roaming\python\python313\site-packages (1.4.0)
Requirement already satisfied: azure-identity>=1.12.0 in c:\users\rajib\appdata\roaming\python\python313\site-packages (from mssql-python) (1.25.3)
Requirement already satisfied: azure-core>=1.31.0 in c:\users\rajib\appdata\roaming\python\python313\site-packages (from azure-identity>=1.12.0->mssql-python) (1.39.0)
Requirement already satisfied: cryptography>=2.5 in c:\programdata\anaconda3\lib\site-packages (from azure-identity>=1.12.0->mssql-python) (46.0.3)
Requirement already satisfied: msal>=1.35.1 in c:\users\rajib\appdata\roaming\python\python313\site-packages (from azure-identity>=1.12.0->mssql-python) (1.35.1)
Requirement already satisfied: msal-extensions>=1.2.0 in c:\users\rajib\appdata\roaming\python\python313\site-packages (from azure-identity>=1.12.0->mssql-python) (1.3.1)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from azure-identity>=1.12.0->mssql-python) (4.15.0)
Requirement already satisfied: requests>=2.21.0 in c:\programdata\anaconda3\lib\site-packages (from azure-core>=1.31.0->azure-identity>=1.12.0->mssql-python) (2.32.5)
Requirement already satisfied: cffi>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from cryptography>=2.5->azure-identity>=1.12.0->mssql-python) (2.0.0)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=2.5->azure-identity>=1.12.0->mssql-python) (2.23)
Requirement already satisfied: PyJWT<3,>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from PyJWT[crypto]<3,>=1.0.0->msal>=1.35.1->azure-identity>=1.12.0->mssql-python) (2.10.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.21.0->azure-core>=1.31.0->azure-identity>=1.12.0->mssql-python) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.21.0->azure-core>=1.31.0->azure-identity>=1.12.0->mssql-python) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.21.0->azure-core>=1.31.0->azure-identity>=1.12.0->mssql-python) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.21.0->azure-core>=1.31.0->azure-identity>=1.12.0->mssql-python) (2025.11.12)

In [56]:
import pandas as pd
from sqlalchemy import create_engine
import urllib

# 1. Your specific connection details from the image
# 'r' before the string handles the backslashes correctly
server = r'DESKTOP-BQDNLBO\SQLEXPRESS'
database = 'customer_behavior'
driver = 'ODBC Driver 17 for SQL Server'

# 2. Build the connection string for Windows Authentication
# We remove username/password and add 'Trusted_Connection=yes'
params = urllib.parse.quote_plus(
    f"DRIVER={{{driver}}};"
    f"SERVER={server};"
    f"DATABASE={database};"
    f"Trusted_Connection=yes;"
    f"TrustServerCertificate=yes;"
)

# 3. Create the engine
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

# 4. Write and Read back
try:
    df.to_sql("customer", engine, if_exists="replace", index=False)
    print("✅ Data successfully stored in 'customer' table.")
    
    # Verification query
    result = pd.read_sql("SELECT TOP 5 * FROM customer", engine)
    print(result)
except Exception as e:
    print(f"❌ Error: {e}")

C:\ProgramData\anaconda3\Lib\site-packages\pandas\io\sql.py:1648: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  con = self.exit_stack.enter_context(con.connect())

✅ Data successfully stored in 'customer' table.
   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases   aged_group  purchase_frequency_days
0            Fortnightly  Middle-aged                     14.0
1            Fortnightly  Young Adult                     14.0
2                 Weekly  Middle-aged                      7.0
3                 Weekly  Young Adult                      7.0
4               Annually  Middle-aged                    365.0